# 现代C++的异常处理

https://docs.microsoft.com/en-us/cpp/cpp/errors-and-exception-handling-modern-cpp?view=vs-2019



categories 类别

recognize 认识

在现代C ++中，在大多数情况下，报告和处理逻辑错误和运行时错误的首选方法是使用**异常**。当堆栈可能在检测错误的函数和具有知道如何处理错误的上下文的函数之间包含多个函数调用时尤其如此。异常为代码提供了一种正式的，定义明确的方法，用于检测错误以将信息传递到调用堆栈。

程序错误一般被分为两种：因程序错误（programming mistakes）导致的逻辑错误，比如“超出范围”错误，另一种是运行时错误，这是超出了程序员控制的错误，比如“网络服务不可用”错误。

在现代c++中使用异常因为以下原因：

- 异常迫使调用代码意识到一个错误条件而后处理它，未被处理的异常将终止程序的执行
- 异常跳转到可以处理错误的调用堆栈中的点。中间函数可以让异常传播。它们不必与其他层协调。
- 抛出异常后，异常堆栈展开机制会根据定义良好的规则销毁作用域中的所有对象。
- 异常让在检测错误的代码和处理错误的代码之间进行清晰的分离。



代码展示

```c++
#include <iostream>
#include <stdexcept>
#include <limits>

using namespace std;

void MyFunc(int c) {
    if (c > numeric_limits<char>::max())
        throw invalid_argument("MyFunc argument too large for char");
}

int main(int argc, char const *argv[]) {
    try {
        MyFunc(256);
    } catch (invalid_argument &e) {
        cerr << e.what() << endl;
        return -1;
    }
    return 0;
}
```

在`try`代码块中，如果一个异常被`throw`，那么他将被捕获在第一个和它的抛出的异常类型一致`catch`代码块中，换句话说，代码从try代码块中跳到了catch代码块中。如果没有可用的catch代码块可用，那么系统将调用`std::terminate`来终止程序，在C++中，任何类型都可以被抛出，但是，我们建议只抛出直接或间接继承于`std::exception`类型的数据。

在设计代码时记住以下要点：

- 使用断言asserts检查那些不可能出现的错误。使用异常检查那些可能出现的错误。
- 当处理错误的代码可能与通过一个或多个中间函数调用检测到错误的代码分开时，请使用异常。当处理错误的代码与检测到错误的代码紧密耦合时，请考虑是否在性能关键循环中使用错误代码。
- 对每个可能抛出或者传播异常的函数，提供以下三个保证中的一个：强壮保证，基础保证，或者无抛出保证。https://docs.microsoft.com/en-us/cpp/cpp/how-to-design-for-exception-safety?view=vs-2019
- 按值抛出异常，按引用接收异常，不要捕获你不能处理的异常
- 不要使用那些在C++11中被弃用的表达式，
- 使用他们提供的标准库中的异常类型，从[exception Class](https://docs.microsoft.com/en-us/cpp/standard-library/exception-class?view=vs-2019)中继续
- 不要允许异常从析构函数或者内存释放函数中逃出



## 异常与断言

异常和断言是两种不同的机制，用于检测程序中的运行时错误。使用断言来测试开发过程中的条件，如果所有代码都正确则应该永远不会出现这种情况。使用异常处理此类错误毫无意义，因为错误表明代码中的某些内容必须修复，并且不代表程序必须在运行时恢复的条件。断言在语句处停止执行，以便您可以在调试器中检查程序状态;异常从第一个适当的catch处理程序继续执行。使用异常检查运行时可能发生的错误情况，即使代码正确，例如“找不到文件”或“内存不足”。您可能希望从这些条件中恢复，即使恢复只是将消息输出到日志并结束程序。始终使用异常检查公共函数的参数。即使您的函数没有错误，您也可能无法完全控制用户可能传递给它的参数。



## 异常安全的类

使用以下建议保证构建异常安全的类：

- 使用智能指针或者其他RAII类型的封装去管理所有的资源；避免在你的类的析构函数中使用资源管理功能，因为如果你的构造函数抛出了异常，析构函数可能不会被调用。不过，如果该类是仅控制一个资源的专用资源管理器，那么使用析构函数来管理资源是可以接受的。
- 理解在一个基类的构造函数中被抛出的异常不可能在子类的构造函数中被吞掉，如果你想在子类的构造函数中转换和重新抛出基类的异常，使用try代码块。
- 考虑是否在一个使用智能指针封装的数据成员存储所有的类的状态，特别是如果一个类有“允许初始化失败”的概念时，尽管C++允许有不初始化的数据成员，但它不支持不初始化或者部分初始化的类实例。一个构造函数要么成功要么失败，没有一个对象会在构造函数完成前被创建。
- 不要允许任何异常从析构函数中逃出，一个基本的C++名言是：析构函数应该从不允许一个异常传递到调用堆栈，如果某个析构函数必须执行一个潜在的异常抛出操作，那么它必须在一个try catch代码块中执行以及吞下这个异常，标准库为它定义的所有析构函数提供此保证。



## [Difference between using try-Catch exception handler and if else condition check? [duplicate\]](https://stackoverflow.com/questions/18307737/difference-between-using-try-catch-exception-handler-and-if-else-condition-check)



## when to use exception

Writing exception-safe code in C++ is not so much about using lots of try { } catch { } blocks. It's about documenting what kind of guarantees your code provides.

I recommend reading Herb Sutter's [Guru Of The Week](http://www.gotw.ca/gotw/index.htm) series, in particular installments 59, 60 and 61.

To summarize, there are three levels of exception safety you can provide:

- Basic: When your code throws an exception, your code does not leak resources, and objects remain destructible.
- Strong: When your code throws an exception, it leaves the state of the application unchanged.
- No throw: Your code never throws exceptions.





## Windows 结构化异常处理



在Microsoft C / C ++ Optimizing Compiler中，它们是使用**__try**和**__except实现的**。











































































